
import { SubscriptionFeatures } from '@/types/subscriptionTypes';

export const SUBSCRIPTION_FEATURES: Record<string, SubscriptionFeatures> = {
  free: {
    hasAdvancedScheduling: false,
    hasAnalytics: false,
    hasPrioritySupport: false,
    hasUnlimitedGeneration: false,
    hasAdvancedAI: false,
    hasBrandVoice: false,
    hasTeamCollaboration: false,
    hasCustomTemplates: false,
    hasAPIAccess: false,
    hasWhiteLabel: false,
    hasHashtagResearch: false,
    hasContentCalendar: false,
    hasAdvancedBrandVoice: false,
    maxContentPerMonth: 5,
    maxBrandVoices: 1,
    maxTeamMembers: 1,
    platforms: ['instagram', 'twitter', 'facebook'],
    templates: ['basic_post', 'announcement']
  },
  starter: {
    hasAdvancedScheduling: true,
    hasAnalytics: true,
    hasPrioritySupport: false,
    hasUnlimitedGeneration: false,
    hasAdvancedAI: false,
    hasBrandVoice: true,
    hasTeamCollaboration: false,
    hasCustomTemplates: false,
    hasAPIAccess: false,
    hasWhiteLabel: false,
    hasHashtagResearch: true,
    hasContentCalendar: true,
    hasAdvancedBrandVoice: false,
    maxContentPerMonth: 50,
    maxBrandVoices: 3,
    maxTeamMembers: 1,
    platforms: ['instagram', 'twitter', 'facebook', 'linkedin'],
    templates: ['basic_post', 'announcement', 'promotional', 'educational']
  },
  creator: {
    hasAdvancedScheduling: true,
    hasAnalytics: true,
    hasPrioritySupport: true,
    hasUnlimitedGeneration: false,
    hasAdvancedAI: true,
    hasBrandVoice: true,
    hasTeamCollaboration: true,
    hasCustomTemplates: true,
    hasAPIAccess: false,
    hasWhiteLabel: false,
    hasHashtagResearch: true,
    hasContentCalendar: true,
    hasAdvancedBrandVoice: true,
    maxContentPerMonth: 200,
    maxBrandVoices: 10,
    maxTeamMembers: 3,
    platforms: ['instagram', 'twitter', 'facebook', 'linkedin', 'tiktok', 'youtube'],
    templates: ['basic_post', 'announcement', 'promotional', 'educational', 'video_script', 'story']
  },
  premium: {
    hasAdvancedScheduling: true,
    hasAnalytics: true,
    hasPrioritySupport: true,
    hasUnlimitedGeneration: true,
    hasAdvancedAI: true,
    hasBrandVoice: true,
    hasTeamCollaboration: true,
    hasCustomTemplates: true,
    hasAPIAccess: true,
    hasWhiteLabel: false,
    hasHashtagResearch: true,
    hasContentCalendar: true,
    hasAdvancedBrandVoice: true,
    maxContentPerMonth: 999999,
    maxBrandVoices: 25,
    maxTeamMembers: 10,
    platforms: ['instagram', 'twitter', 'facebook', 'linkedin', 'tiktok', 'youtube', 'pinterest'],
    templates: ['basic_post', 'announcement', 'promotional', 'educational', 'video_script', 'story', 'thread', 'carousel']
  },
  enterprise: {
    hasAdvancedScheduling: true,
    hasAnalytics: true,
    hasPrioritySupport: true,
    hasUnlimitedGeneration: true,
    hasAdvancedAI: true,
    hasBrandVoice: true,
    hasTeamCollaboration: true,
    hasCustomTemplates: true,
    hasAPIAccess: true,
    hasWhiteLabel: true,
    hasHashtagResearch: true,
    hasContentCalendar: true,
    hasAdvancedBrandVoice: true,
    maxContentPerMonth: 999999,
    maxBrandVoices: 999999,
    maxTeamMembers: 999999,
    platforms: ['instagram', 'twitter', 'facebook', 'linkedin', 'tiktok', 'youtube', 'pinterest', 'snapchat'],
    templates: ['basic_post', 'announcement', 'promotional', 'educational', 'video_script', 'story', 'thread', 'carousel', 'custom']
  }
};

export const BUSINESS_USER_FEATURES: SubscriptionFeatures = {
  hasAdvancedScheduling: true,
  hasAnalytics: true,
  hasPrioritySupport: true,
  hasUnlimitedGeneration: true,
  hasAdvancedAI: true,
  hasBrandVoice: true,
  hasTeamCollaboration: true,
  hasCustomTemplates: true,
  hasAPIAccess: true,
  hasWhiteLabel: true,
  hasHashtagResearch: true,
  hasContentCalendar: true,
  hasAdvancedBrandVoice: true,
  maxContentPerMonth: 999999,
  maxBrandVoices: 999999,
  maxTeamMembers: 999999,
  platforms: ['instagram', 'twitter', 'facebook', 'linkedin', 'tiktok', 'youtube', 'pinterest', 'snapchat'],
  templates: ['basic_post', 'announcement', 'promotional', 'educational', 'video_script', 'story', 'thread', 'carousel', 'custom']
};
