
import { SubscriptionFeatures, SubscriptionTier } from "@/types/subscriptionTypes";

export const SUBSCRIPTION_FEATURES: Record<SubscriptionTier, SubscriptionFeatures> = {
  free: {
    hasAdvancedScheduling: false,
    hasAnalytics: false,
    hasPrioritySupport: false,
    hasUnlimitedGeneration: false,
    hasAdvancedAI: false,
    hasBrandVoice: false,
    hasTeamCollaboration: false,
    hasCustomTemplates: false,
    hasAPIAccess: false,
    hasWhiteLabel: false,
    hasHashtagResearch: false,
    hasContentCalendar: false,
    hasAdvancedBrandVoice: false,
    maxContentPerMonth: 10,
    maxBrandVoices: 1,
    maxTeamMembers: 1,
    platforms: ['twitter', 'facebook'],
    templates: ['basic-post', 'quote-inspiration', 'brand-story']
  },
  starter: {
    hasAdvancedScheduling: true,
    hasAnalytics: false,
    hasPrioritySupport: false,
    hasUnlimitedGeneration: false,
    hasAdvancedAI: true,
    hasBrandVoice: true,
    hasTeamCollaboration: false,
    hasCustomTemplates: false,
    hasAPIAccess: false,
    hasWhiteLabel: false,
    hasHashtagResearch: true,
    hasContentCalendar: true,
    hasAdvancedBrandVoice: false,
    maxContentPerMonth: 100,
    maxBrandVoices: 3,
    maxTeamMembers: 1,
    platforms: ['twitter', 'facebook', 'instagram', 'linkedin', 'tiktok', 'youtube'],
    templates: ['basic-post', 'quote-inspiration', 'brand-story', 'product-launch', 'tutorial-post', 'behind-the-scenes', 'community-post', 'educational-carousel']
  },
  creator: {
    hasAdvancedScheduling: true,
    hasAnalytics: false,
    hasPrioritySupport: false,
    hasUnlimitedGeneration: false,
    hasAdvancedAI: true,
    hasBrandVoice: true,
    hasTeamCollaboration: false,
    hasCustomTemplates: false,
    hasAPIAccess: false,
    hasWhiteLabel: false,
    hasHashtagResearch: true,
    hasContentCalendar: true,
    hasAdvancedBrandVoice: false,
    maxContentPerMonth: 50,
    maxBrandVoices: 3,
    maxTeamMembers: 1,
    platforms: ['twitter', 'facebook', 'instagram', 'linkedin', 'tiktok', 'youtube'],
    templates: ['basic-post', 'quote-inspiration', 'brand-story', 'product-launch', 'tutorial-post', 'behind-the-scenes', 'community-post', 'educational-carousel']
  },
  premium: {
    hasAdvancedScheduling: true,
    hasAnalytics: true,
    hasPrioritySupport: true,
    hasUnlimitedGeneration: true,
    hasAdvancedAI: true,
    hasBrandVoice: true,
    hasTeamCollaboration: true,
    hasCustomTemplates: true,
    hasAPIAccess: false,
    hasWhiteLabel: false,
    hasHashtagResearch: true,
    hasContentCalendar: true,
    hasAdvancedBrandVoice: true,
    maxContentPerMonth: 500,
    maxBrandVoices: 10,
    maxTeamMembers: 5,
    platforms: ['twitter', 'facebook', 'instagram', 'linkedin', 'tiktok', 'youtube', 'pinterest'],
    templates: ['basic-post', 'quote-inspiration', 'brand-story', 'product-launch', 'tutorial-post', 'behind-the-scenes', 'community-post', 'educational-carousel', 'custom-template-1', 'custom-template-2']
  },
  enterprise: {
    hasAdvancedScheduling: true,
    hasAnalytics: true,
    hasPrioritySupport: true,
    hasUnlimitedGeneration: true,
    hasAdvancedAI: true,
    hasBrandVoice: true,
    hasTeamCollaboration: true,
    hasCustomTemplates: true,
    hasAPIAccess: true,
    hasWhiteLabel: true,
    hasHashtagResearch: true,
    hasContentCalendar: true,
    hasAdvancedBrandVoice: true,
    maxContentPerMonth: Infinity,
    maxBrandVoices: Infinity,
    maxTeamMembers: Infinity,
    platforms: ['twitter', 'facebook', 'instagram', 'linkedin', 'tiktok', 'youtube', 'pinterest', 'snapchat', 'reddit'],
    templates: ['basic-post', 'quote-inspiration', 'brand-story', 'product-launch', 'tutorial-post', 'behind-the-scenes', 'community-post', 'educational-carousel', 'custom-template-1', 'custom-template-2', 'custom-template-3']
  }
};

export const BUSINESS_USER_FEATURES: SubscriptionFeatures = {
  hasAdvancedScheduling: true,
  hasAnalytics: true,
  hasPrioritySupport: true,
  hasUnlimitedGeneration: true,
  hasAdvancedAI: true,
  hasBrandVoice: true,
  hasTeamCollaboration: true,
  hasCustomTemplates: true,
  hasAPIAccess: true,
  hasWhiteLabel: true,
  hasHashtagResearch: true,
  hasContentCalendar: true,
  hasAdvancedBrandVoice: true,
  maxContentPerMonth: Infinity,
  maxBrandVoices: Infinity,
  maxTeamMembers: Infinity,
  platforms: ['twitter', 'facebook', 'instagram', 'linkedin', 'tiktok', 'youtube', 'pinterest', 'snapchat', 'reddit'],
  templates: ['basic-post', 'quote-inspiration', 'brand-story', 'product-launch', 'tutorial-post', 'behind-the-scenes', 'community-post', 'educational-carousel', 'custom-template-1', 'custom-template-2', 'custom-template-3']
};
