// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfznphaajdjqpocimpnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmem5waGFhamRqcXBvY2ltcG5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzIyMTMsImV4cCI6MjA2Mzg0ODIxM30.c19EBiAlXnxTPEc3Af7FRTtPLauKoz3MGswi_fHp4CU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);